version: "3.9"
services:
  livekit:
    # image: livekit/livekit-server:latest
    image: livekit/livekit-server:v1.8.0
    command: ["--dev", "--bind", "0.0.0.0"]
    ports:
      - "7880:7880"
      - "7881:7881/udp"
    environment:
      NODE_IP: 192.168.1.4
      UDP_PORT: 7881
    networks:
      - edu-net
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - edu-net
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - edu-net
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - edu-net
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CREATE_TOPICS: "my-app:1:1"
    networks:
      - edu-net
  migrator:
    build:
      context: .
      dockerfile: ./Docker/migration/Dockerfile
    networks:
      - edu-net
    depends_on:
      - db
  server:
    build:
      context: .
      dockerfile: ./Docker/http/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    env_file:
      - ./apps/http/.env
    networks:
      - edu-net
    depends_on:
      - livekit
      - db
      - redis
  ws:
    build:
      context: .
      dockerfile: ./Docker/ws/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./apps/webSocket/.env
    networks:
      - edu-net
    depends_on:
      - db
      - redis
      - kafka
  worker_1:
    build:
      context: .
      dockerfile: ./Docker/w_1/Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    env_file:
      - ./apps/worker_1/.env
    networks:
      - edu-net
    depends_on:
      - db
      - redis
  worker_2:
    build:
      context: .
      dockerfile: ./Docker/w_2/Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    env_file:
      - ./apps/worker_2/.env
    networks:
      - edu-net
    depends_on:
      - db
      - kafka

networks:
  edu-net:
    driver: bridge
